///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EmergencyModel {
/*
{
  "id": 1,
  "user_id": "1",
  "emergency_name": "2062927690",
  "emergency_phone": "AUTH_1q1t7sdzhv",
  "emergency_address": "408408",
}
*/

  int? id;
  int? userId;
  String? emergencyName;
  String? emergencyPhone;
  String? emergencyAddress;

  EmergencyModel({
    this.id,
    this.userId,
    this.emergencyName,
    this.emergencyPhone,
    this.emergencyAddress,
  });
  EmergencyModel.fromMap(json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toInt();
    emergencyName = json['emergency_name']?.toString();
    emergencyPhone = json['emergency_phone']?.toString();
    emergencyAddress = json['emergency_address']?.toString();
  }
  
  Map<String, dynamic> toMap() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['emergency_name'] = userId;
    data['emergency_phone'] = userId;
    data['emergency_address'] = userId;
    return data;
  }
}
