///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TransactionModel {
/*
{
  "id": 1,
  "user_id": 1,
  "payment_ref": "grwfkbnixy",
  "amount": "3000",
  "effect": "dr",
  "payment_for": "withdrawal",
  "payment_source": "withdrawal",
  "remark": "grwfkbnixy",
  "created_at": "01 Sep, 10:41 pm"
}
*/

  int? id;
  int? userId;
  String? paymentRef;
  String? amount;
  String? effect;
  String? paymentFor;
  String? paymentSource;
  String? remark;
  String? createdAt;

  TransactionModel({
    this.id,
    this.userId,
    this.paymentRef,
    this.amount,
    this.effect,
    this.paymentFor,
    this.paymentSource,
    this.remark,
    this.createdAt,
  });
  TransactionModel.fromMap(json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toInt();
    paymentRef = json['payment_ref']?.toString();
    amount = json['amount']?.toString();
    effect = json['effect']?.toString();
    paymentFor = json['payment_for']?.toString();
    paymentSource = json['payment_source']?.toString();
    remark = json['remark']?.toString();
    createdAt = json['created_at']?.toString();
  }
  Map<String, dynamic> toMap() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['payment_ref'] = paymentRef;
    data['amount'] = amount;
    data['effect'] = effect;
    data['payment_for'] = paymentFor;
    data['payment_source'] = paymentSource;
    data['remark'] = remark;
    data['created_at'] = createdAt;
    return data;
  }
}
