// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/entities/ridedb_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7605573563559531096),
      name: 'RideDetails',
      lastPropertyId: const IdUid(4, 6262785369768071222),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1934397881120450082),
            name: 'hasRide',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 7891814579923703940),
            name: 'rideId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7164667072588834622),
            name: 'rideType',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6262785369768071222),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7605573563559531096),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    RideDetails: EntityDefinition<RideDetails>(
        model: _entities[0],
        toOneRelations: (RideDetails object) => [],
        toManyRelations: (RideDetails object) => {},
        getId: (RideDetails object) => object.id,
        setId: (RideDetails object, int id) {
          object.id = id;
        },
        objectToFB: (RideDetails object, fb.Builder fbb) {
          final rideIdOffset = fbb.writeString(object.rideId);
          final rideTypeOffset = fbb.writeString(object.rideType);
          fbb.startTable(5);
          fbb.addBool(0, object.hasRide);
          fbb.addOffset(1, rideIdOffset);
          fbb.addOffset(2, rideTypeOffset);
          fbb.addInt64(3, object.id ?? 0);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = RideDetails(
              hasRide:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 4, false),
              rideId: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              rideType: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''))
            ..id = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 10);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [RideDetails] entity fields to define ObjectBox queries.
class RideDetails_ {
  /// see [RideDetails.hasRide]
  static final hasRide =
      QueryBooleanProperty<RideDetails>(_entities[0].properties[0]);

  /// see [RideDetails.rideId]
  static final rideId =
      QueryStringProperty<RideDetails>(_entities[0].properties[1]);

  /// see [RideDetails.rideType]
  static final rideType =
      QueryStringProperty<RideDetails>(_entities[0].properties[2]);

  /// see [RideDetails.id]
  static final id =
      QueryIntegerProperty<RideDetails>(_entities[0].properties[3]);
}
